[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[build]
  publish = "_site"
  command = "jekyll build && cd functions/staticman && npm install"
  functions = "functions"
